apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply-new-pipeline
spec:
  resources:
    inputs:
  params:
    - name: script-to-apply-yamls
      description: Script to apply all YAMLs
      type: string
      default: "./tekton/apply_yamls.sh"
  steps:
    - name: script-to-apply-yamls
      image: ubuntu
      workingDir: /
      script: date        
      securityContext:
        runAsUser: 0
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: apply-new-pipeline
spec:
  params:
  resources:
  tasks:
  - name: apply-new-pipeline
    taskRef:
      name: apply-new-pipeline
    params:
    resources:
      inputs:
