apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
    name: build-and-deploy-kabanero-website-pipelinerun
spec:
    pipelineRef:
        name: build-and-deploy-kabanero-website
    resources:
        -
            name: git-repo
            resourceRef: {name: kabanero-website-repo}
        -
            name: target-image
            resourceRef: {name: kabanero-website-image}
    params:
        -
            name: ibm_cloud_organization
            value: dewan.ishtiaque@hotmail.com
        -
            name: ibm_cloud_space
            value: dev
        -
            name: ibm_cloud_api
            value: 'https://cloud.ibm.com'
        -
            name: ibm_cloud_api_key_secret
            value: ibmcloud-api-key-kabanero-website
        -
            name: docs_git_url
            value: 'https://github.com/kabanero-io/docs.git'
        -
            name: guides_git_url
            value: 'https://github.com/nastacio/guides.git'
        -
            name: github_token_secret
            value: git-pat-kabanero-website
